name: Build & Release

on:
  push:
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:

  build-and-release-android-apks:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:

      - name: checkout branch
        uses: actions/checkout@v3

      - name: setup flutter
        uses: subosito/flutter-action@v2.12.0
        with:
          channel: 'stable'
      
      - name: Setup Java toolchain (Only Android target)
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"    

      - name: Setup Android keystore
        run: |
          echo "${{ secrets.SIGNING_KEY_STORE_BASE64 }}" | base64 -di > android/app/upload-keystore.jks
          echo "${{ secrets.SIGNING_KEY_PROPERTIES }}" > android/key.properties

      - name: flutter pub get
        run: flutter pub get

      - name: build android apks
        run: |
          flutter build apk --release --split-per-abi --dart-define=cronetHttpNoPlay=true
          cd build/app/outputs/flutter-apk
          mv app-arm64-v8a-release.apk Omni-View-${{ github.ref_name }}-android-arm64-v8a.apk
          mv app-armeabi-v7a-release.apk Omni-View-${{ github.ref_name }}-android-armeabi-v7a.apk
          mv app-x86_64-release.apk Omni-View-${{ github.ref_name }}-android-x86_64.apk

      - name: upload artifact android apks
        uses: actions/upload-artifact@v3
        with:
          path: "build/app/outputs/flutter-apk/Omni-View-*.apk"

      - name: release packages android apks
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/Omni-View-*.apk"
          allowUpdates: true


  build-and-release-ios-ipa:
    permissions:
      contents: write
    runs-on: macos-latest
    steps:
      # Checkout branch
      - name: checkout branch
        uses: actions/checkout@v3

      - name: setup flutter
        uses: subosito/flutter-action@v2.12.0
        with:
          channel: 'stable'

      - name: flutter pub get
        run: flutter pub get

      - name: build ios
        run: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app-release.ipa Payload
          mv app-release.ipa Omni-View-${{ github.ref_name }}-ios.ipa

      - name: upload artifact ios ipa
        uses: actions/upload-artifact@v3
        with:
          path: "build/ios/iphoneos/Omni-View-*.ipa"

      - name: release package ios ipa
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/ios/iphoneos/Omni-View-*.ipa"
          allowUpdates: true


  build-and-release-macos-dmg:
    permissions:
      contents: write
    runs-on: macos-latest
    steps:

      - name: checkout branch
        uses: actions/checkout@v3

      - name: setup flutter
        uses: subosito/flutter-action@v2.12.0
        with:
          channel: 'stable'

      - name: flutter pub get
        run: flutter pub get

      - name: build macos
        run: |
          cd macos
          pod update
          cd ..
          flutter build macos --release
          brew install create-dmg 
          create-dmg --volname Omni-View-${{ github.ref_name }}-macos --window-pos 200 120 --window-size 800 450 --icon-size 100 --app-drop-link 600 185 Omni-View-${{ github.ref_name }}-macos.dmg build/macos/Build/Products/Release/Omni-View.app

      - name: upload artifact macos dmg
        uses: actions/upload-artifact@v3
        with:
          path: "/Users/runner/work/Omni-View/Omni-View/*.dmg"

      - name: release package macos dmg
        uses: ncipollo/release-action@v1
        with:
          artifacts: "/Users/runner/work/Omni-View/Omni-View/*.dmg"
          allowUpdates: true


  build-and-release-windows-zip:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:

      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.12.0
        with:
          channel: 'stable'

      - name: Flutter pub get
        run: flutter pub get

      - name: Build Windows
        run: |
          flutter build windows --release
          $DestDir = "build\windows\Omni-View-${{ github.ref_name }}-windows"
          $SrcDir = "build\windows\x64\runner\Release"
          New-Item -Path $DestDir -ItemType Directory
          Copy-Item $SrcDir\* -Recurse $DestDir
          Copy-Item -Filter *.dll -Path windows\* -Destination $DestDir -Force
          Compress-Archive -Path $DestDir -DestinationPath build\windows\Omni-View-${{ github.ref_name }}-windows.zip

      - name: Upload artifact Windows ZIP
        uses: actions/upload-artifact@v3
        with:
          path: build\windows\Omni-View-*.zip

      - name: Release package Windows ZIP
        uses: ncipollo/release-action@v1
        with:
          artifacts: build\windows\Omni-View-*.zip
          allowUpdates: true

          
  build-and-release-linux-zip:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      
      - name: checkout branch
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install webkit2gtk-4.1 clang cmake ninja-build pkg-config libgtk-3-dev mpv libmpv-dev dpkg-dev

      - name: setup flutter
        uses: subosito/flutter-action@v2.12.0
        with:
          channel: 'stable'


      - name: flutter pub get
        run: flutter pub get

      - name: build linux
        run: flutter build linux --verbose
      - name: Zip 
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          filename: Omni-View-${{ github.ref_name }}-linux.zip
          directory: build/linux/x64/release/bundle
      
      - name: upload artifact linux zip
        uses: actions/upload-artifact@v3
        with:
          path: build/linux/x64/release/bundle/Omni-View-*.zip
      - name: release packages linux zip
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/linux/x64/release/bundle/Omni-View-*.zip
          allowUpdates: true


  build-and-release-linux-appimage:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      
      - name: checkout branch
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install webkit2gtk-4.1 clang cmake ninja-build pkg-config libgtk-3-dev mpv libmpv-dev dpkg-dev

      - name: setup flutter
        uses: subosito/flutter-action@v2.12.0
        with:
          channel: 'stable'

      - name: flutter pub get
        run: flutter pub get

      - name: build linux
        run: |  

          sudo apt install -y libfuse2
          
          curl -JOL https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod a+x appimagetool-x86_64.AppImage
          mv appimagetool-x86_64.AppImage appimagetool

          flutter build linux --release

          patchelf --replace-needed libmpv.so.1 libmpv.so build/linux/x64/release/bundle/lib/libmedia_kit_video_plugin.so
          patchelf --replace-needed libmpv.so.1 libmpv.so build/linux/x64/release/bundle/lib/libmedia_kit_native_event_loop.so
                    
          mv build/linux/x64/release/bundle/{Omni-View,AppRun}
          cp linux/appimage/* build/linux/x64/release/bundle/
          ./appimagetool build/linux/x64/release/bundle/
          mv *.AppImage build/Omni-View-${{ github.ref_name }}-linux.AppImage

      - name: upload artifact linux appimage
        uses: actions/upload-artifact@v3
        with:
          path: build/Omni-View-*.AppImage
      - name: Rrelease packages appimage
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/Omni-View-*.AppImage
          allowUpdates: true
